package com.yan.common.subscription.mapper;

import com.yan.common.evaluate.model.Evaluate;
import com.yan.common.subscription.model.Subscription;
import com.yan.common.user.model.SysUserExample;

import java.util.List;

public interface SubscriptionMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER
     *
     * @mbg.generated Thu Sep 14 18:04:32 CST 2017
     */
    List<Subscription> selectByExample(SysUserExample example);


}