package com.yan.common.news.mapper;

import com.yan.common.news.model.News;
import com.yan.common.user.model.SysUser;
import com.yan.common.user.model.SysUserExample;
import com.yan.common.user.model.SysUserKey;
import org.apache.ibatis.annotations.Param;

import java.util.ArrayList;
import java.util.List;

public interface NewsMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER
     *
     * @mbg.generated Thu Sep 14 18:04:32 CST 2017
     */
    List<News> selectByExample(SysUserExample example);
    int updateByPrimaryKey(ArrayList ids);
    int deleteByPrimaryKey(List ids);

}